export { default as Email } from "./Email";
export { default as Envelope } from "./Envelope";
export { default as Facebook } from "./Facebook";
export { default as Failed } from "./Failed";
export { default as Share } from "./Share";
export { default as Success } from "./Success";
export { default as Twitter } from "./Twitter";
export { default as Whatsapp } from "./Whatsapp";
export { default as Youtube } from "./Youtube";
